version: "3.8"

services:
  backend:
    build:
      context: ./backend
    container_name: techrca-backend
    environment:
      - OPENAI_API_KEY=your-openai-api-key
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/techrca
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
    container_name: techrca-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

  db:
    image: postgres:14
    container_name: techrca-db
    environment:
      POSTGRES_DB: techrca
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
